apiVersion: apps/v1
kind: Deployment
metadata:
  name: charging-stations-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charging-stations-ms
  template:
    metadata:
      labels:
        app: charging-stations-ms
      annotations:        
        'consul.hashicorp.com/connect-inject': 'false'
    spec:
      containers:
        - image: anzx10/charging-stations-microservice:v5.0
          name: charging-stations-ms
          env:
            - name: DB_HOST
              value: tai.db.elephantsql.com
            - name: DB_NAME
              value: syypqwkg
            - name: DB_USERNAME
              value: syypqwkg
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: charging-stations-ms
                  key: db-password

              # Consul
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP

          ports:
            - containerPort: 80
              name: server
              protocol: TCP
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
---

apiVersion: v1
kind: Service
metadata:
  name: charging-stations-ms
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: charging-stations-ms
